general.live_config_reload = true

[cursor.style]
blinking = "Never"

[env]
TERM = "xterm-256color"

[scrolling]
history = 100000
multiplier = 3

[selection]
save_to_clipboard = true
semantic_escape_chars = ",â”‚`|:\"' ()[]{}<>\t"

[window]
decorations = "Buttonless"
startup_mode = "SimpleFullscreen"

[window.dimensions]
columns = 145
lines = 40

[window.padding]
x = 25
y = 25 
